name: publish-build

on:
  push:
    branches:
      - master
defaults:
  run:
    working-directory: .

jobs:
  build:
    runs-on: ${{ matrix.os }}
    needs: [version]

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - run: git pull origin master
