name: publish-build

on:
  push:
    branches:
      - master
defaults:
  run:
    working-directory: .

jobs:
  build:
    runs-on: ${{ matrix.os }}
    needs: [version]

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - run: git pull origin main

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Prepare for app notarization
      - run: npm install
      - run: npm run electron:build
        env:
          CI: false
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
